export const originCities = [
  { city: 'Москва', iata: 'MOW' },
  { city: 'Санкт-Петербург', iata: 'LED' },
  { city: 'Калининград', iata: 'KGD' },
  { city: 'Казань', iata: 'KZN' },
  { city: 'Самара', iata: 'KUF' },
  { city: 'Екатеринбург', iata: 'SVX' },
  { city: 'Новосибирск', iata: 'OVB' },
  { city: 'Краснодар', iata: 'KRR' },
  { city: 'Ростов-на-Дону', iata: 'ROV' },
  { city: 'Сочи', iata: 'AER' },
  { city: 'Нижний Новгород', iata: 'GOJ' },
  { city: 'Оренбург', iata: 'REN' },
  { city: 'Грозный', iata: 'GRV' },
  { city: 'Махачкала', iata: 'MCX' },
  { city: 'Уфа', iata: 'UFA' },
  { city: 'Воронеж', iata: 'VOZ' },
  { city: 'Волгоград', iata: 'VOG' },
]
